name: run tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    # Use the base-devel image of Arch Linux for building pyalpm
    container: archlinux:base-devel

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python deps
      run: python -m pip install -U pytest pytest-asyncio nvchecker requests lxml PyYAML pyalpm structlog python_prctl fluent.runtime

    - name: Run pytest
      run: pytest
